/**
 * Bot Config Generator - Auto-injects credentials and generates deployment configs
 * Used by admin to generate deployment-ready configs for bots
 */

import { IStorage } from "./storage";

export async function generateBotConfig(storage: IStorage, botId: string, userId: string) {
  const bot = await storage.getBotById(botId);
  if (!bot || bot.userId !== userId) {
    throw new Error("Bot not found or access denied");
  }

  const user = await storage.getUser(userId);
  if (!user) {
    throw new Error("User not found");
  }

  // Auto-inject config
  const config = {
    // Bot credentials (SENSITIVE - never log these)
    botToken: bot.botToken,
    telegramId: bot.telegramId,
    
    // User info
    userId: user.visibleId || userId,
    userTelegramId: user.telegramId,
    
    // Premium status
    isPremium: user.premiumStatus === "premium",
    premiumExpiry: user.premiumExpiry?.toISOString(),
    
    // Bot info
    botId: bot.id,
    botVersion: bot.version,
    
    // API endpoints
    apiBaseUrl: "https://kifzldev-cloud.devpanel.me/api",
    webhookUrl: `https://kifzldev-cloud.devpanel.me/api/webhook/bot/${bot.id}`,
    
    // Server config
    environment: "production",
    serverTime: new Date().toISOString(),
  };

  return config;
}

/**
 * Generate deployment script for Bot V1
 */
export function generateV1DeploymentScript(config: any): string {
  const configJson = JSON.stringify(config).replace(/'/g, "\\'");
  
  return `#!/bin/bash
# Bot V1 (NodeJS) - Deployment Script
# Generated by KIFZLDEV NEO-2025 Platform

export BOT_CONFIG='${configJson}'
export NODE_ENV=production

cd /path/to/bots/v1
npm install --production
node bootstrap.js
`;
}

/**
 * Generate deployment script for Bot V2
 */
export function generateV2DeploymentScript(config: any): string {
  const lines = [
    "#!/bin/bash",
    "# Bot V2 (Python) - Deployment Script",
    "# Generated by KIFZLDEV NEO-2025 Platform",
    "",
    `export BOT_CONFIG='${JSON.stringify(config)}'`,
    `export TELEGRAM_BOT_TOKEN='${config.botToken}'`,
    `export OWNER_ID=${config.telegramId}`,
    `export BOT_ID='${config.botId}'`,
    `export USER_ID='${config.userId}'`,
    `export IS_PREMIUM=${config.isPremium ? 'true' : 'false'}`,
    "",
    "cd /path/to/bots/v2",
    "pip install -r requirements.txt",
    "python bootstrap.py",
  ];
  
  return lines.join("\n");
}

/**
 * Generate Docker Compose for both bots
 */
export function generateDockerCompose(v1Config: any, v2Config: any): string {
  const template = `version: '3.8'

services:
  bot-v1:
    build:
      context: ./bots/v1
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      BOT_CONFIG: '${JSON.stringify(v1Config)}'
    restart: unless-stopped
    networks:
      - kifzldev
    
  bot-v2:
    build:
      context: ./bots/v2
      dockerfile: Dockerfile
    environment:
      BOT_CONFIG: '${JSON.stringify(v2Config)}'
      TELEGRAM_BOT_TOKEN: '${v2Config.botToken}'
      OWNER_ID: ${v2Config.telegramId}
    restart: unless-stopped
    networks:
      - kifzldev

networks:
  kifzldev:
    driver: bridge
`;
  
  return template;
}
